---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# insertImage

R package: Insert image from file chooser into Markdown. Copy image to project. Addin for RStudio.

Inserts image code with alternative text specified by user in console.  

If image file is not in the project (working directory or subdirectory) the user can copy the image file to the project. An img/ directory is created in the working directory, unless the document is in vignettes/ directory in which case the user can choose to copy to this directory instead.    

Note: On Linux and possibly other OSes, if you are not asked whether to move an image that is not already in your working directory (or sub directory) to your working directory, it might help to *set the working directory* to the folder in which your active document exists.  

By Ludvig R. Olsen,  
Cognitive Science, Aarhus University.  
Started in Feb. 2017  

Contact at:  
r-pkgs@ludvigolsen.dk  


Main functions:   

* insertImage   

## Installation  
Development version:  

> install.packages("devtools")
>
> devtools::install_github("LudvigOlsen/insertImage")  

## Use

* Install package.
* Add key command by going to:   
    - *Tools* > *Addins* > *Browse Addins* > *Keyboard Shortcuts*.  
    - Find **Insert Image** and press its field under *Shortcut*. 
    - Press desired key command.
    - Press *Apply*.
    - Press *Execute*.
* Press chosen key command inside R Markdown document.  

